title: LES PTA
description: Laytonsville Elementary Scool Parent Teacher Association

url: http://aeb.sr/les
baseurl: ""
paginate_path: "/archive/page:num/"
permalink: /:categories/:year/:month/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Events
   url: /events
 - title: Volunteering
   url: /volunteering
 # - title: Minutes
 #   url: /minutes
 # - title: News & Events
 #   url: /news-events
 - title: Contact
   url: /contact
 - title: Join PTA!
   url: /assets/join-pta.docx

social:
   twitter: principalles
   facebook: LaytonsvillePTA

# google_analytics: "UA-58263416-1"
